#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
nohup $OPENSHIFT_REPO_DIR/bin/hugo \
	--bind=$OPENSHIFT_DIY_IP \
	--port=$OPENSHIFT_DIY_PORT \
	--source=$OPENSHIFT_REPO_DIR \
	--destination=$OPENSHIFT_REPO_DIR/public \
	--watch=false \
	--appendPort=false \
	--disableLiveReload=true \
	server |& /usr/bin/logshifter -tag diy &
