baseurl = "http://sub-pop.net/"
languageCode = "en-us"
title = "sub-pop"
theme = "smol"

[author]
	name = "Link Dupont"

[params]
    topmenu="none"

[markup]
  [markup.highlight]
    style = "native"
